### ISSUE TITLE
加K校正？

### ISSUE THREAD

**Issue by Crossing-Light** [LLAA178/mmpi2-CN-normals#1]
对用户有加K校正，而对常模没有加K校正。
测试分数出现了很大的偏离。
以及Mf的女性分数计算方法是T=50-(X-SD)/10，注意50后面的减号。

**Comment by LLAA178** [comment]
感谢你的耐心观察与测试。我测试发现进行K分校正的项目都偏高，然后去掉对用户得分K分校正就正常了，或许这个常模已经进行过K校正了？女性Mf计分也已经修改了。具体可以看最新提交。

**Comment by Crossing-Light** [comment]
感谢！

**Comment by LLAA178** [comment]
我想过给常模加K，因为都是正态分布，均值直接相加，然后标准差应该是取根号下的平方和，这样会稍微有点麻烦并且我不确定这样得到的答案就真实有效。网上对这一块的描述不是很多，而且很多相关网站计算也有偏差。
