### ISSUE TITLE
求问每个子量表的题号的来源 

### ISSUE THREAD

**Issue by wencan** [LLAA178/mmpi2-CN-normals#3]
刚刚在另一个项目，提出了一样的issue：https://github.com/MMPI-CHN/MMPI-CHN.github.io/issues/11
依然拿Si（社会内向）为例
mmpi2-CN-normals的Si题号 与 MMPI-CHN.github.io的一致
与 SHENGYUKing/MMPI_Test 的截然不同

so ……

**Comment by LLAA178** [comment]
![image](https://github.com/user-attachments/assets/27e15975-d572-4035-929e-9daeec7cb1a0)
MMPI-2: Assessing Personality and Psychopathology  这本书里有mmpi2各个量表的题号 我校正了应该是没问题的

**Comment by wencan** [comment]
@LLAA178 这本书里包括567个项目 和 亚列表的题号吗？

https://github.com/MMPI-CHN/MMPI-CHN.github.io/issues/11 请看这里的讨论。有两个版本的567个项目，不知道哪个版本算“标准”的

**Comment by LLAA178** [comment]
你这两个测试都是mmpi的，我这个是mmpi2的。mmpi计分规则和常模都不同，请参考其它资料。

**Comment by wencan** [comment]
我也找到了MMPI-2: Assessing Personality and Psychopathology
看起来比较可信

MMPI-1不是567个项目
但这两个版本都是567个项目
另一个版本是怎么回事呢？中国研究者的本地化版？

**Comment by wencan** [comment]
MMPI-2 的 567个项目，有可信度很高的来源吗？
MMPI-2: Assessing Personality and Psychopathology上只有部分项目——或者因为我的“打开方式”不正确？
